project './platforms/ios/Affinite HR.xcworkspace'

target ‘Affinite HR’ do
  pod 'FirebaseInstanceID'
  pod 'GoogleCloudMessaging'
  pod 'GGLInstanceID'
  pod 'AFNetworking', '~> 3.0'
  pod 'FBSDKCoreKit', '~> 4.9’
end